import Header from '../components/Header';
import Footer from '../components/Footer';
import InvestmentForm from '../components/InvestmentForm';

export default function InvestPage() {
  return (
    <main className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Header />
      
      <section className="py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Invest in Our <span className="bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-400 dark:to-purple-400 text-transparent bg-clip-text">rasta-trendier</span> Strategy
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Put your money to work with our proven algorithmic trading strategy. 
              You earn 90% of all profits, we earn 10%.
            </p>
          </div>
          
          <InvestmentForm />
          
          <div className="max-w-3xl mx-auto mt-16">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Frequently Asked Questions</h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">How does the investment process work?</h3>
                  <p className="mt-2 text-gray-600 dark:text-gray-300">
                    Once you invest, your funds will be allocated to our automated rasta-trendier strategy. 
                    The algorithm will trade on your behalf using proven technical indicators and risk management protocols.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">What is the minimum investment?</h3>
                  <p className="mt-2 text-gray-600 dark:text-gray-300">
                    The minimum investment is $100 USD. There is no maximum limit on your investment.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">How are fees calculated?</h3>
                  <p className="mt-2 text-gray-600 dark:text-gray-300">
                    We only earn when you earn. Our fee is 10% of the profits generated by the strategy. 
                    If there are no profits in a given period, you pay no fees.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">How can I withdraw my investment?</h3>
                  <p className="mt-2 text-gray-600 dark:text-gray-300">
                    You can withdraw your investment at any time from your dashboard. Withdrawal requests are processed within 24-48 hours.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">What are the risks involved?</h3>
                  <p className="mt-2 text-gray-600 dark:text-gray-300">
                    All investments carry risk, and cryptocurrency markets are volatile. While our strategy has historical performance data, 
                    past performance is not indicative of future results. Only invest what you can afford to lose.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </main>
  );
} 